#include "thedc.h"


int check[4]={1,1,1,1};

void get_score(int x,int y){
	int score=0,time=0,i=0;
	move_to_exact(x,y);
	if(S_flag>0){
			score=Position[5+5*Position[0]];
			time=Position[22];
			GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3, 0x08);
			for(;S_flag!=0;){
				for(i=0;i<500;i++);
				if(Position[23]==0x00) return;
				if(Position[22]<(time-7)) break;
				if(Position[5+5*Position[0]]!=score) 	break;
				}
			GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3, 0x0);
			for(i=0;i<4;i++) check[i]=1;

			}
}




int Place()
{
    if(head_local[0]<=128&&head_local[1]<=128)
    {
        if(head_local[0]>=head_local[1]){
            if(head_local[0]>70)
                return 11;
            return 14;
        }
        if(head_local[1]>70)
            return 12;
        return 13;
    }
    if(head_local[0]>128&&head_local[1]<=128){
        if(head_local[0]>=255-head_local[1]){
            if(head_local[1]>70)
                return 22;
            return 23;
        }
        if(255-head_local[0]>70)
             return 21;
        return 24;
    }
    if(head_local[0]>128&&head_local[1]>128)
    {
        if(head_local[0]>=head_local[1]) {
            if(255-head_local[1]>70)
            	return 32;
            return 33;
        }
        if(255-head_local[0]>70)
            return 31;
        return 34;
    }
    if(head_local[0]<128&&head_local[1]>128)
    {
        if(255-head_local[0]>=head_local[1])
        {
            if(255-head_local[1]>70)
            	return 42;
            return 43;
        }

        if(head_local[0]>70)
        	return 41;
        return 44;
    }
    return 0;
}

void target1(int judge)
{

	if(((int)(judge/10))==1)
    {
        if(judge%10==1)
        {
            move_to(96,_Py);
            //move_to_exact(96,_Py);
            get_score(_Px,_Py);
            return;
        }
        if(judge%10==2)
        {
        	move_to(_Px,96);
        	//move_to_exact(_Px,96);
            get_score(_Px,_Py);
        	return;
        }
        if(judge%10==3)
        {
            move_to(head_local[0],110);//竖直移动到II区
            move_to(_Px,96);
            //move_to_exact(_Px,96);
            get_score(_Px,_Py);
        }
        if(judge%10==4)
        {
            move_to(110,head_local[1]);//水平移动到I区
            move_to(96,_Py);
            //move_to_exact(96,_Py);
            get_score(_Px,_Py);
        }
    }
    if(((int)(judge/10))==2)
    {
        if(judge%10==1)
        {
            move_to(96,_Py);
            //move_to_exact(96,_Py);
            get_score(_Px,_Py);
        }
        if(judge%10==2)
        {
            move_to(_Px,96);
            //move_to_exact(_Px,96);
            get_score(_Px,_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],110);
            move_to(_Px,96);
            //move_to_exact(_Px,96);
            get_score(_Px,_Py);
        }
        if(judge%10==4)
        {
            move_to(140,head_local[1]);
            move_to(96,_Py);
            //move_to_exact(96,_Py);
            get_score(_Px,_Py);
        }
    }
    if(((int)(judge/10))==3)
    {
        if(judge%10==1)
        {
            move_to(96,_Py);
            //move_to_exact(96,_Py);
            get_score(_Px,_Py);
        }
        if(judge%10==2)
        {
            move_to(_Px,96);
            //move_to_exact(_Px,96);
            head(_Px,_Py);
            get_score(_Px,_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],110);
            //move_to_exact(_Px,96);
            move_to(_Px,96);
            get_score(_Px,_Py);
        }
        if(judge%10==4)
        {
            move_to(150,head_local[1]);
            //move_to_exact(96,_Py);
            move_to(96,_Py);
            get_score(_Px,_Py);
        }
    }
    if(((int)(judge/10))==4)
    {
        if(judge%10==1)
        {
            move_to(96,_Py);
            //move_to_exact(96,_Py);
            get_score(_Px,_Py);
        }
        if(judge%10==2)
        {
            move_to(_Px,96);
            //move_to_exact(_Px,96);
            get_score(_Px,_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],110);
            move_to(_Px,96);
            //move_to_exact(_Px,96);
            get_score(_Px,_Py);
        }
        if(judge%10==4)
        {
            move_to(110,head_local[1]);
            move_to(96,_Py);
            //move_to_exact(96,_Py);
            get_score(_Px,_Py);
        }
    }
}

void target2(int judge)
{
    if(((int)(judge/10))==1)
    {
        if(judge%10==1)
        {
            move_to(150,_Py);
            //move_to_exact(150,_Py);
            get_score(255-_Px,_Py);
        }
        if(judge%10==2)
        {
            move_to(255-_Px,96);
            //move_to_exact(255-_Px,96);
            get_score(255-_Px,_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],110);//竖直移动到II区
            move_to(255-_Px,96);
            //move_to_exact(255-_Px,96);
            head(255-_Px,_Py);
            get_score(255-_Px,_Py);
        }
        if(judge%10==4)
        {
            move_to(110,head_local[1]);//水平移动到I区
            move_to(150,_Py);
            //move_to_exact(150,_Py);
            get_score(255-_Px,_Py);
        }
    }
    if(((int)(judge/10))==2)
    {
        if(judge%10==1)
        {
            move_to(150,_Py);
            //move_to_exact(150,_Py);
            get_score(255-_Px,_Py);
        }
        if(judge%10==2)
        {
            move_to(255-_Px,96);
            //move_to_exact(255-_Px,96);
            get_score(255-_Px,_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],110);
            move_to(255-_Px,96);
            //move_to_exact(255-_Px,96);
            get_score(255-_Px,_Py);
        }
        if(judge%10==4)
        {
            move_to(150,head_local[1]);
            move_to(150,_Py);
            //move_to_exact(150,_Py);
            get_score(255-_Px,_Py);
        }
    }
    if(((int)(judge/10))==3)
    {
        if(judge%10==1)
        {
            move_to(150,_Py);
            //move_to_exact(150,_Py);
            get_score(255-_Px,_Py);
        }
        if(judge%10==2)
        {
            move_to(255-_Px,96);
            //move_to_exact(255-_Px,96);
            get_score(255-_Px,_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],150);
            move_to(255-_Px,96);
            //move_to_exact(255-_Px,96);
            get_score(255-_Px,_Py);
        }
        if(judge%10==4)
        {
            move_to(110,head_local[1]);
            move_to(150,_Py);
            //move_to_exact(150,_Py);
            get_score(255-_Px,_Py);
        }
    }
    if(((int)(judge/10))==4)
    {
        if(judge%10==1)
        {
            move_to(150,_Py);
            //move_to_exact(150,_Py);
            get_score(255-_Px,_Py);
        }
        if(judge%10==2)
        {
            move_to(255-_Px,96);
            //move_to_exact(255-_Px,96);
            get_score(255-_Px,_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],150);
            move_to(255-_Px,96);
            //move_to_exact(255-_Px,96);
            get_score(255-_Px,_Py);
        }
        if(judge%10==4)
        {
            move_to(150,head_local[1]);
            move_to(150,_Py);
            //move_to_exact(150,_Py);
            get_score(255-_Px,_Py);
        }
    }
}


void target3(int judge)
{
    if(((int)(judge/10))==1)
    {
        if(judge%10==1)
        {
            move_to(150,255-_Py);
            //move_to_exact(150,255-_Py);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==2)
        {
            move_to(255-_Px,150);
            //move_to_exact(255-_Px,150);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],110);//竖直移动到II区
            move_to(255-_Px,150);
            //move_to_exact(255-_Px,150);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==4)
        {
            move_to(110,head_local[1]);//水平移动到I区
            move_to(150,255-_Py);
            //move_to_exact(150,255-_Py);
            get_score(255-_Px,255-_Py);
        }
    }
    if(((int)(judge/10))==2)
    {
        if(judge%10==1)
        {
            move_to(150,255-_Py);
            //move_to_exact(150,255-_Py);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==2)
        {
            move_to(255-_Px,150);
            //move_to_exact(255-_Px,150);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],110);
            move_to(255-_Px,150);
            //move_to_exact(255-_Px,150);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==4)
        {
            move_to(150,head_local[1]);
            move_to(150,255-_Py);
            //move_to_exact(150,255-_Py);
            get_score(255-_Px,255-_Py);
        }
    }
    if(((int)(judge/10))==3)
    {
        if(judge%10==1)
        {
            move_to(150,255-_Py);
            //move_to_exact(150,255-_Py);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==2)
        {
            move_to(255-_Px,150);
            //move_to_exact(255-_Px,150);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],150);
            move_to(255-_Px,150);
            //move_to_exact(255-_Px,150);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==4)
        {
            move_to(110,head_local[1]);
            move_to(150,255-_Py);
            //move_to_exact(150,255-_Py);
            get_score(255-_Px,255-_Py);
        }
    }
    if(((int)(judge/10))==4)
    {
        if(judge%10==1)
        {
            move_to(150,255-_Py);
            //move_to_exact(150,255-_Py);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==2)
        {
            move_to(255-_Px,150);
            //move_to_exact(255-_Px,150);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],150);
            move_to(255-_Px,150);
            //move_to_exact(255-_Px,150);
            get_score(255-_Px,255-_Py);
        }
        if(judge%10==4)
        {
            move_to(150,head_local[1]);
            move_to(150,255-_Py);
            //move_to_exact(150,255-_Py);
            get_score(255-_Px,255-_Py);
        }
    }
}

void target4(int judge)
{
    if(((int)(judge/10))==1)
    {
        if(judge%10==1)
        {
            move_to(110,255-_Py);
            //move_to_exact(110,255-_Py);
            get_score(_Px,255-_Py);
        }
        if(judge%10==2)
        {
            move_to(_Px,165);
            //move_to_exact(_Px,165);
            get_score(_Px,255-_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],110);//竖直移动到II区
            move_to(_Px,165);
            //move_to_exact(_Px,165);
            get_score(_Px,255-_Py);
        }
        if(judge%10==4)
        {
            move_to(110,head_local[1]);//水平移动到I区
            move_to(110,255-_Py);
            //move_to_exact(110,255-_Py);
            get_score(_Px,255-_Py);
        }
    }
    if(((int)(judge/10))==2)
    {
        if(judge%10==1)
        {
            move_to(110,255-_Py);
            //move_to_exact(110,255-_Py);
            get_score(_Px,255-_Py);
        }
        if(judge%10==2)
        {
            move_to(_Px,165);
            //move_to_exact(_Px,165);
            get_score(_Px,255-_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],110);
            move_to(_Px,165);
            //move_to_exact(_Px,165);
            get_score(_Px,255-_Py);
        }
        if(judge%10==4)
        {
            move_to(150,head_local[1]);
            move_to(110,255-_Py);
            //move_to_exact(110,255-_Py);
            get_score(_Px,255-_Py);
        }
    }
    if(((int)(judge/10))==3)
    {
        if(judge%10==1)
        {
            move_to(110,255-_Py);
            //move_to_exact(110,255-_Py);
            get_score(_Px,255-_Py);
        }
        if(judge%10==2)
        {
            move_to(_Px,165);
            //move_to_exact(_Px,165);
            get_score(_Px,255-_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],150);
            move_to(_Px,165);
            //move_to_exact(_Px,165);
            get_score(_Px,255-_Py);
        }
        if(judge%10==4)
        {
            move_to(110,head_local[1]);
            move_to(110,255-_Py);
            //move_to_exact(110,255-_Py);
            get_score(_Px,255-_Py);
        }
    }
    if(((int)(judge/10))==4)
    {
        if(judge%10==1)
        {
            move_to(110,255-_Py);
            //move_to_exact(110,255-_Py);
            get_score(_Px,255-_Py);
        }
        if(judge%10==2)
        {
            move_to(_Px,165);
            //move_to_exact(_Px,165);
            get_score(_Px,255-_Py);
        }
        if(judge%10==3)
        {
            move_to(head_local[0],150);
            move_to(_Px,165);
            //move_to_exact(_Px,165);
            get_score(_Px,255-_Py);
        }
        if(judge%10==4)
        {
            move_to(150,head_local[1]);
            move_to(110,255-_Py);
            //move_to_exact(110,255-_Py);
            get_score(_Px,255-_Py);
        }
    }
}

